@startuml Context
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

System_Boundary(platform, "IoT Monitoring Platform") {
    Container(api_gateway, "API Gateway", "Spring Cloud Gateway", "Routing and authorization")
    Container(api_orchestrator, "API Orchestrator", "Spring Boot", "Executes: event, device and command services")
    Container(command_service, "Command Service", "Go + gRPC", "Receives commands and sends them to devices. Works with a separate PostgreSQL DB")
    Container(device_service, "Device Service", "Spring Boot + ShardingSphere-JDBC", "CRUD API used by devices. Uses internal sharding via JDBC")
    Container(event_service, "Event Service", "Spring Boot", "Reads events from Cassandra")
    Container(redis, "Redis", "In-memory Cache", "Requests caching")
    Container(events_collector, "Events Collector", "Spring Boot", "Kafka -> Cassandra + device-id")
    Container(device_collector, "Device Collector", "Spring Boot", "Receives device-id and saves it in PostgreSQL")
    Container(failed_events_processor, "Failed Events Processor", "Spring Boot", "DLT -> JSON in MinIO")
    Container(minio, "MinIO", "Cloud Storage", "Saving DLT errors")
    Container(cassandra_cluster, "Cassandra Cluster", "NoSQL", "Events storage")

    Container_Ext(iot_devices, "IoT Devices", "Embedded devices", "Send telemetry and receive commands")
    Container_Ext(keycloak, "Keycloak", "OAuth2", "Authentication/Authorization")
    Container_Ext(postgres_commands, "PostgreSQL Commands", "Relational DB", "Separate DB for commands. Used by Go service")
    Container_Ext(postgres_devices, "PostgreSQL Devices", "Relational DB", "Sharded DB for devices data. Synchronous replication per shard")
    Container_Ext(kafka, "Kafka Cluster", "Kafka", "event/dlt/device-id topics")
}

Rel(api_gateway, keycloak, "OIDC authorization")
Rel(api_gateway, api_orchestrator, "REST", "JWT")
Rel(api_orchestrator, command_service, "gRPC", "Command sending")
Rel(api_orchestrator, device_service, "REST")
Rel(api_orchestrator, event_service, "REST")
Rel(api_orchestrator, redis, "Caching")
Rel(device_service, postgres_devices, "Sharded JDBC", "write/read")
Rel(iot_devices, command_service, "gRPC", "Receiving commands")
Rel(command_service, postgres_commands, "JDBC", "write/read")
Rel(event_service, cassandra_cluster, "Read", "events")
Rel(events_collector, cassandra_cluster, "Write", "events")
Rel(events_collector, kafka, "Consume", "events-topic")
Rel(events_collector, kafka, "Produce", "device-id topic")
Rel(events_collector, kafka, "Produce", "dlt-topic")
Rel(device_collector, kafka, "Consume", "device-id topic")
Rel(failed_events_processor, kafka, "Consume", "dlt-topic")
Rel(failed_events_processor, minio, "Save", "JSON")

@enduml